name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python -m pip install flake8
      - run: flake8 src --max-line-length=120 --extend-ignore=E203,W503
      - run: python - <<'PY'
import importlib, sys
for m in ["spotipy","pandas","numpy"]:
    importlib.import_module(m)
print("Imports OK")
PY
